---
title: "Selecting a Color Palette For Data Visualization"
author: "Wang"
date: "2024-08-08"
output: 
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: false
    highlight: tango
    output_dir: "./"
---

```{r setup1, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup2 }
library(LorMe)

"color_scheme.Rmd"
```

# Function

color_scheme(Plan, expand = NULL, names = NULL, show = T)

color_scheme() can generate color scheme from nine color scheme database and expand into colorRamp

```{r eval=FALSE}

#' @param Plan Character, 'Plan1' to 'Plan10' are optional.
#' @param expand Numeric, default: NULL. Numeric indicating numbers to expand color scheme into colorRamp.
#' @param names Character string. Names to assign for color scheme.
#' @param show Logical. If TRUE, show assigned color in plot panel. Default: TRUE.
```

# Examples

## built-in color schemes

```{r, echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan1")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan2")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan3")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan4")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan5")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan6")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan7")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan8")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan9")
```

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(Plan = "Plan10")
```

## expand according to your color

```{r , echo=TRUE,fig.width=3,fig.height=3}
my_col<- color_scheme(c('#fe5c5c','#ffff99','#75abde'),10)
```
